env: "local"
storage_path: "./repository.db"

auth:
  hash_salt: "hash_salt"
  signing_key: "signing_key"
  token_ttl: 8640000s

listen:
  type: "port"
  host: "0.0.0.0"
  port: "1234"  
  timeout: 4s
  idle_timeout: 60s
